do $$
declare
  seed record;
  make_uuid uuid;
  model_uuid uuid;
begin
  for seed in
    select * from (values
      ('Toyota','toyota','JP','https://www.carlogos.org/car-logos/toyota-logo.png',10),
      ('Honda','honda','JP','https://www.carlogos.org/car-logos/honda-logo.png',20),
      ('Isuzu','isuzu','JP','https://www.carlogos.org/car-logos/isuzu-logo.png',30),
      ('Mitsubishi','mitsubishi','JP','https://www.carlogos.org/car-logos/mitsubishi-logo.png',40),
      ('Ford','ford','US','https://www.carlogos.org/car-logos/ford-logo.png',50),
      ('Mazda','mazda','JP','https://www.carlogos.org/car-logos/mazda-logo.png',60),
      ('Suzuki','suzuki','JP','https://www.carlogos.org/car-logos/suzuki-logo.png',70),
      ('MG','mg','CN','https://www.carlogos.org/car-logos/mg-logo.png',80),
      ('Nissan','nissan','JP','https://www.carlogos.org/car-logos/nissan-logo.png',90),
      ('Hyundai','hyundai','KR','https://www.carlogos.org/car-logos/hyundai-logo.png',100),
      ('AION','aion','CN',null,210),
      ('Audi','audi','DE','https://www.carlogos.org/car-logos/audi-logo.png',220),
      ('Benelli','benelli','IT',null,230),
      ('BMW','bmw','DE','https://www.carlogos.org/car-logos/bmw-logo.png',240),
      ('BYD','byd','CN','https://www.carlogos.org/car-logos/byd-logo.png',250),
      ('CFMoto','cfmoto','CN',null,260),
      ('Changan','changan','CN',null,270),
      ('Chery','chery','CN','https://www.carlogos.org/car-logos/chery-logo.png',280),
      ('Chevrolet','chevrolet','US','https://www.carlogos.org/car-logos/chevrolet-logo.png',290),
      ('Daihatsu','daihatsu','JP','https://www.carlogos.org/car-logos/daihatsu-logo.png',300),
      ('DFSK','dfsk','CN',null,310),
      ('Foton','foton','CN',null,320),
      ('Geely','geely','CN','https://www.carlogos.org/car-logos/geely-logo.png',330),
      ('GPX','gpx','TH',null,340),
      ('GWM','gwm','CN',null,350),
      ('Jeep','jeep','US','https://www.carlogos.org/car-logos/jeep-logo.png',360),
      ('Kawasaki','kawasaki','JP',null,370),
      ('Kia','kia','KR','https://www.carlogos.org/car-logos/kia-logo.png',380),
      ('KTM','ktm','AT',null,390),
      ('Mercedes-Benz','mercedes-benz','DE','https://www.carlogos.org/car-logos/mercedes-benz-logo.png',400),
      ('Neta','neta','CN',null,410),
      ('ORA','ora','CN',null,420),
      ('Royal Enfield','royal-enfield','IN',null,430),
      ('Subaru','subaru','JP','https://www.carlogos.org/car-logos/subaru-logo.png',440),
      ('Volkswagen','volkswagen','DE','https://www.carlogos.org/car-logos/volkswagen-logo.png',450),
      ('Volvo','volvo','SE','https://www.carlogos.org/car-logos/volvo-logo.png',460),
      ('Yamaha','yamaha','JP',null,470),
      ('Zontes','zontes','CN',null,480)
    ) as v(name, slug, origin_country, logo_url, sort_order)
  loop
    insert into public.vehicle_makes (name, slug, origin_country, logo_url, sort_order, is_active)
    values (seed.name, seed.slug, seed.origin_country, seed.logo_url, seed.sort_order, true)
    on conflict (slug) do update set
      name = excluded.name,
      origin_country = excluded.origin_country,
      logo_url = coalesce(public.vehicle_makes.logo_url, excluded.logo_url),
      sort_order = excluded.sort_order,
      is_active = true;
  end loop;

  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/toyota-logo.png' where slug = 'toyota';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/honda-logo.png' where slug = 'honda';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/ford-logo.png' where slug = 'ford';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/mazda-logo.png' where slug = 'mazda';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/nissan-logo.png' where slug = 'nissan';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/mitsubishi-logo.png' where slug = 'mitsubishi';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/isuzu-logo.png' where slug = 'isuzu';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/suzuki-logo.png' where slug = 'suzuki';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/hyundai-logo.png' where slug = 'hyundai';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/kia-logo.png' where slug = 'kia';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/subaru-logo.png' where slug = 'subaru';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/volkswagen-logo.png' where slug = 'volkswagen';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/bmw-logo.png' where slug = 'bmw';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/mercedes-benz-logo.png' where slug = 'mercedes-benz';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/audi-logo.png' where slug = 'audi';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/volvo-logo.png' where slug = 'volvo';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/chevrolet-logo.png' where slug = 'chevrolet';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/jeep-logo.png' where slug = 'jeep';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/byd-logo.png' where slug = 'byd';
  update public.vehicle_makes set logo_url = 'https://www.carlogos.org/car-logos/mg-logo.png' where slug = 'mg';

  for seed in
    select * from (values
      ('toyota','Yaris','car','hatchback','J / E / G / Sport',2006,null,1200,'Automatic','petrol',5,'FWD'),
      ('toyota','Yaris Ativ','car','sedan','Entry / Sport / Smart / Premium / GR Sport',2017,null,1200,'Automatic','petrol',5,'FWD'),
      ('toyota','Vios','car','sedan','J / E / G / S',2005,2022,1500,'Automatic','petrol',5,'FWD'),
      ('toyota','Corolla Altis','car','sedan','G / V / GR Sport / Hybrid',2005,null,1800,'Automatic','petrol/hybrid',5,'FWD'),
      ('toyota','Corolla Cross','car','suv','Sport / Premium / HEV / GR Sport',2020,null,1800,'Automatic','petrol/hybrid',5,'FWD'),
      ('toyota','Yaris Cross','car','suv','Smart / Premium / HEV',2023,null,1500,'Automatic','hybrid',5,'FWD'),
      ('toyota','Camry','car','sedan','G / V / Hybrid / Premium',2005,null,2500,'Automatic','petrol/hybrid',5,'FWD'),
      ('toyota','Prius','car','hatchback','Hybrid',2010,2015,1800,'Automatic','hybrid',5,'FWD'),
      ('toyota','C-HR','car','suv','Hybrid Mid / High',2018,2023,1800,'Automatic','hybrid',5,'FWD'),
      ('toyota','Hilux Vigo','car','pickup','Single Cab / Smart Cab / Double Cab',2005,2015,2500,'Manual/Automatic','diesel',5,'RWD/4WD'),
      ('toyota','Hilux Revo','car','pickup','Standard / Prerunner / Rocco / GR Sport',2015,null,2400,'Manual/Automatic','diesel',5,'RWD/4WD'),
      ('toyota','Fortuner','car','ppv','G / V / Legender / GR Sport',2005,null,2400,'Automatic','diesel',7,'RWD/4WD'),
      ('toyota','Innova','car','mpv','E / G / V / Crysta / Zenix',2005,null,2000,'Automatic','petrol/hybrid',7,'RWD/FWD'),
      ('toyota','Avanza','car','mpv','E / G',2005,2022,1500,'Automatic','petrol',7,'RWD'),
      ('toyota','Veloz','car','mpv','Smart / Premium',2022,null,1500,'Automatic','petrol',7,'FWD'),
      ('toyota','Sienta','car','mpv','G / V',2016,2022,1500,'Automatic','petrol',7,'FWD'),
      ('toyota','Alphard','car','van','Executive Lounge / Hybrid',2005,null,2500,'Automatic','petrol/hybrid',7,'FWD/AWD'),
      ('toyota','Vellfire','car','van','Z / Hybrid',2008,null,2500,'Automatic','petrol/hybrid',7,'FWD/AWD'),
      ('toyota','Hiace','van','van','Commuter / GL / Panel Van',2005,null,2800,'Manual/Automatic','diesel',12,'RWD'),
      ('toyota','Commuter','van','van','Standard / GL',2005,null,2800,'Manual/Automatic','diesel',12,'RWD'),
      ('honda','City','car','sedan','S / V / SV / RS / e:HEV',2005,null,1000,'Automatic','petrol/hybrid',5,'FWD'),
      ('honda','City Hatchback','car','hatchback','S+ / SV / RS / e:HEV',2021,null,1000,'Automatic','petrol/hybrid',5,'FWD'),
      ('honda','Civic','car','sedan','E / EL / RS / e:HEV',2005,null,1500,'Automatic','petrol/hybrid',5,'FWD'),
      ('honda','Accord','car','sedan','E / EL / TECH / e:HEV',2005,null,2000,'Automatic','petrol/hybrid',5,'FWD'),
      ('honda','Jazz','car','hatchback','S / V / SV / RS',2005,2021,1500,'Automatic','petrol',5,'FWD'),
      ('honda','Brio','car','hatchback','S / V',2011,2019,1200,'Automatic','petrol',5,'FWD'),
      ('honda','Brio Amaze','car','sedan','S / V',2013,2019,1200,'Automatic','petrol',5,'FWD'),
      ('honda','Mobilio','car','mpv','S / V / RS',2014,2021,1500,'Automatic','petrol',7,'FWD'),
      ('honda','BR-V','car','suv','V / SV',2016,null,1500,'Automatic','petrol',7,'FWD'),
      ('honda','HR-V','car','suv','E / EL / RS / e:HEV',2015,null,1500,'Automatic','petrol/hybrid',5,'FWD'),
      ('honda','CR-V','car','suv','E / EL / RS / e:HEV',2005,null,1500,'Automatic','petrol/hybrid',5,'FWD/AWD'),
      ('honda','WR-V','car','suv','SV / RS',2023,null,1500,'Automatic','petrol',5,'FWD'),
      ('isuzu','D-Max','car','pickup','Spark / Spacecab / Cab4 / V-Cross',2005,null,1900,'Manual/Automatic','diesel',5,'RWD/4WD'),
      ('isuzu','MU-X','car','ppv','Active / Elegant / Ultimate / RS',2013,null,1900,'Automatic','diesel',7,'RWD/4WD'),
      ('mitsubishi','Mirage','car','hatchback','GLX / GLS / Limited',2012,2024,1200,'Automatic','petrol',5,'FWD'),
      ('mitsubishi','Attrage','car','sedan','GLX / GLS / Limited',2013,2024,1200,'Automatic','petrol',5,'FWD'),
      ('mitsubishi','Triton','car','pickup','Single Cab / Mega Cab / Double Cab / Athlete',2005,null,2400,'Manual/Automatic','diesel',5,'RWD/4WD'),
      ('mitsubishi','Pajero Sport','car','ppv','GT / Elite / 4WD',2008,null,2400,'Automatic','diesel',7,'RWD/4WD'),
      ('mitsubishi','Xpander','car','mpv','GLS / GT / Cross',2018,null,1500,'Automatic','petrol',7,'FWD'),
      ('mitsubishi','Outlander PHEV','car','suv','GT-Premium / PHEV',2020,2023,2400,'Automatic','plug-in hybrid',5,'AWD'),
      ('ford','Ranger','car','pickup','XL / XLS / XLT / Wildtrak / Raptor',2005,null,2000,'Manual/Automatic','diesel',5,'RWD/4WD'),
      ('ford','Everest','car','ppv','Trend / Titanium / Sport / Platinum',2005,null,2000,'Automatic','diesel',7,'RWD/4WD'),
      ('ford','Fiesta','car','hatchback','Trend / Sport / Titanium',2010,2018,1500,'Automatic','petrol',5,'FWD'),
      ('ford','Focus','car','hatchback','Trend / Sport / Titanium',2005,2019,2000,'Automatic','petrol',5,'FWD'),
      ('ford','EcoSport','car','suv','Trend / Titanium',2014,2022,1500,'Automatic','petrol',5,'FWD'),
      ('ford','Territory','car','suv','Trend / Titanium',2021,null,1500,'Automatic','petrol',5,'FWD'),
      ('mazda','Mazda 2','car','hatchback/sedan','C / S / SP / XDL',2009,null,1300,'Automatic','petrol/diesel',5,'FWD'),
      ('mazda','Mazda 3','car','sedan/hatchback','C / S / SP',2005,null,2000,'Automatic','petrol',5,'FWD'),
      ('mazda','Mazda 6','car','sedan','C / S / SP',2005,2022,2500,'Automatic','petrol',5,'FWD'),
      ('mazda','CX-3','car','suv','Base / Comfort / Proactive / SP',2015,null,2000,'Automatic','petrol',5,'FWD'),
      ('mazda','CX-30','car','suv','C / S / SP',2020,null,2000,'Automatic','petrol',5,'FWD'),
      ('mazda','CX-5','car','suv','C / S / SP / XDL',2013,null,2000,'Automatic','petrol/diesel',5,'FWD/AWD'),
      ('mazda','CX-8','car','suv','XDL / SP',2019,null,2500,'Automatic','petrol/diesel',6,'FWD/AWD'),
      ('mazda','BT-50','car','pickup','Standard / Freestyle / Double Cab',2006,null,1900,'Manual/Automatic','diesel',5,'RWD/4WD'),
      ('suzuki','Swift','car','hatchback','GA / GL / GLX / RS',2005,null,1200,'Automatic','petrol',5,'FWD'),
      ('suzuki','Celerio','car','hatchback','GA / GL / GX',2014,2023,1000,'Automatic','petrol',5,'FWD'),
      ('suzuki','Ciaz','car','sedan','GL / GLX / RS',2015,2022,1250,'Automatic','petrol',5,'FWD'),
      ('suzuki','Ertiga','car','mpv','GL / GX / Hybrid',2013,null,1500,'Automatic','petrol/mild hybrid',7,'FWD'),
      ('suzuki','XL7','car','suv','GLX',2020,null,1500,'Automatic','petrol/mild hybrid',7,'FWD'),
      ('suzuki','Carry','van','pickup/van','Standard',2005,null,1500,'Manual','petrol',2,'RWD'),
      ('suzuki','Jimny','car','suv','Sierra / GLX',2019,null,1500,'Automatic','petrol',4,'4WD'),
      ('mg','MG3','car','hatchback','C / D / X / Hybrid+',2015,null,1500,'Automatic','petrol/hybrid',5,'FWD'),
      ('mg','MG5','car','sedan','C / D / X',2015,null,1500,'Automatic','petrol',5,'FWD'),
      ('mg','MG6','car','sedan','D / X / PHEV',2015,2021,1800,'Automatic','petrol/plug-in hybrid',5,'FWD'),
      ('mg','ZS','car','suv','C / D / X / V',2017,null,1500,'Automatic','petrol',5,'FWD'),
      ('mg','ZS EV','car','suv','D / X',2019,null,null,'Automatic','electric',5,'FWD'),
      ('mg','HS','car','suv','C / D / X / PHEV',2019,null,1500,'Automatic','petrol/plug-in hybrid',5,'FWD'),
      ('mg','EP','car','wagon','EV',2021,2023,null,'Automatic','electric',5,'FWD'),
      ('mg','ES','car','wagon','EV',2023,null,null,'Automatic','electric',5,'FWD'),
      ('mg','Maxus 9','van','van','EV',2023,null,null,'Automatic','electric',7,'FWD'),
      ('mg','Cyberster','car','roadster','EV',2024,null,null,'Automatic','electric',2,'RWD/AWD'),
      ('nissan','Almera','car','sedan','E / EL / V / VL / Sportech',2011,null,1000,'Automatic','petrol',5,'FWD'),
      ('nissan','March','car','hatchback','S / E / V / VL',2010,2022,1200,'Automatic','petrol',5,'FWD'),
      ('nissan','Sylphy','car','sedan','E / V / VL',2012,2020,1800,'Automatic','petrol',5,'FWD'),
      ('nissan','Teana','car','sedan','XL / XV',2005,2019,2500,'Automatic','petrol',5,'FWD'),
      ('nissan','Kicks','car','suv','E / V / VL / Autech e-POWER',2020,null,1200,'Automatic','hybrid',5,'FWD'),
      ('nissan','X-Trail','car','suv','V / VL / e-POWER',2005,null,1500,'Automatic','petrol/hybrid',5,'FWD/AWD'),
      ('nissan','Terra','car','ppv','E / VL / Sport',2018,null,2300,'Automatic','diesel',7,'RWD/4WD'),
      ('nissan','Navara','car','pickup','Single Cab / King Cab / Calibre / PRO-4X',2005,null,2300,'Manual/Automatic','diesel',5,'RWD/4WD'),
      ('nissan','Leaf','car','hatchback','EV',2019,null,null,'Automatic','electric',5,'FWD'),
      ('hyundai','H-1','van','van','Deluxe / Elite / Touring',2008,2021,2500,'Automatic','diesel',11,'RWD'),
      ('hyundai','Grand Starex','van','van','VIP / Premium',2008,2021,2500,'Automatic','diesel',11,'RWD'),
      ('hyundai','Staria','van','van','S / SEL / Premium',2021,null,2200,'Automatic','diesel',11,'FWD'),
      ('hyundai','Tucson','car','suv','GLS / Premium',2005,null,2000,'Automatic','petrol/diesel',5,'FWD/AWD'),
      ('hyundai','Santa Fe','car','suv','Premium',2005,null,2200,'Automatic','diesel/hybrid',7,'FWD/AWD'),
      ('hyundai','Creta','car','suv','Trend / Style',2022,null,1500,'Automatic','petrol',5,'FWD'),
      ('hyundai','Ioniq 5','car','suv','EV',2022,null,null,'Automatic','electric',5,'RWD/AWD'),
      ('kia','Carnival','van','van','LX / EX / SXL / VIP',2005,null,2200,'Automatic','diesel',7,'FWD'),
      ('kia','Sorento','car','suv','EX / Premium',2005,null,2200,'Automatic','diesel/hybrid',7,'FWD/AWD'),
      ('kia','Sportage','car','suv','EX / GT-Line',2005,null,2000,'Automatic','petrol/diesel',5,'FWD/AWD'),
      ('kia','Picanto','car','hatchback','LX / EX',2005,2018,1200,'Automatic','petrol',5,'FWD'),
      ('kia','EV5','car','suv','EV',2024,null,null,'Automatic','electric',5,'FWD/AWD'),
      ('kia','EV6','car','suv','EV',2022,null,null,'Automatic','electric',5,'RWD/AWD'),
      ('subaru','XV','car','suv','2.0i / Eyesight',2012,2023,2000,'Automatic','petrol',5,'AWD'),
      ('subaru','Crosstrek','car','suv','2.0i-S Eyesight',2023,null,2000,'Automatic','petrol',5,'AWD'),
      ('subaru','Forester','car','suv','2.0i / GT / Eyesight',2005,null,2000,'Automatic','petrol',5,'AWD'),
      ('subaru','Outback','car','wagon','Eyesight',2005,null,2500,'Automatic','petrol',5,'AWD'),
      ('subaru','BRZ','car','coupe','Standard / tS',2012,null,2400,'Manual/Automatic','petrol',4,'RWD'),
      ('daihatsu','Mira','car','hatchback','Standard',2005,2018,660,'Automatic','petrol',4,'FWD'),
      ('daihatsu','Terios','car','suv','Standard',2005,2017,1500,'Automatic','petrol',7,'RWD/4WD'),
      ('daihatsu','Gran Max','van','van/pickup','Standard',2007,null,1500,'Manual','petrol',2,'RWD'),
      ('chevrolet','Aveo','car','sedan/hatchback','LS / LT',2005,2013,1400,'Automatic','petrol',5,'FWD'),
      ('chevrolet','Sonic','car','sedan/hatchback','LS / LT / LTZ',2012,2015,1400,'Automatic','petrol',5,'FWD'),
      ('chevrolet','Cruze','car','sedan','LS / LT / LTZ',2010,2015,1800,'Automatic','petrol',5,'FWD'),
      ('chevrolet','Captiva','car','suv','LS / LT / Premier',2007,2020,2400,'Automatic','petrol/diesel',7,'FWD/AWD'),
      ('chevrolet','Colorado','car','pickup','Single Cab / X-Cab / Crew Cab / High Country',2005,2020,2500,'Manual/Automatic','diesel',5,'RWD/4WD'),
      ('chevrolet','Trailblazer','car','ppv','LT / LTZ / Z71',2012,2020,2500,'Automatic','diesel',7,'RWD/4WD'),
      ('jeep','Wrangler','car','suv','Sport / Sahara / Rubicon',2005,null,2000,'Automatic','petrol/plug-in hybrid',5,'4WD'),
      ('jeep','Grand Cherokee','car','suv','Limited / Summit',2005,null,3600,'Automatic','petrol/plug-in hybrid',5,'4WD'),
      ('jeep','Compass','car','suv','Limited',2017,null,2400,'Automatic','petrol',5,'FWD/4WD'),
      ('mercedes-benz','A-Class','car','hatchback/sedan','A 200 / A 250 / AMG',2005,null,1300,'Automatic','petrol',5,'FWD/AWD'),
      ('mercedes-benz','C-Class','car','sedan','C 180 / C 200 / C 220d / C 300e / AMG',2005,null,1500,'Automatic','petrol/diesel/plug-in hybrid',5,'RWD/AWD'),
      ('mercedes-benz','E-Class','car','sedan','E 220d / E 300e / AMG',2005,null,2000,'Automatic','diesel/plug-in hybrid',5,'RWD'),
      ('mercedes-benz','S-Class','car','sedan','S 350d / S 500e / Maybach',2005,null,3000,'Automatic','diesel/plug-in hybrid',5,'RWD/AWD'),
      ('mercedes-benz','GLA','car','suv','GLA 200 / GLA 250 / AMG',2014,null,1300,'Automatic','petrol',5,'FWD/AWD'),
      ('mercedes-benz','GLB','car','suv','GLB 200 / GLB 250',2020,null,1300,'Automatic','petrol',7,'FWD/AWD'),
      ('mercedes-benz','GLC','car','suv','GLC 220d / GLC 300e / Coupe / AMG',2015,null,2000,'Automatic','diesel/plug-in hybrid',5,'AWD'),
      ('mercedes-benz','GLE','car','suv','GLE 300d / GLE 350de / AMG',2005,null,3000,'Automatic','diesel/plug-in hybrid',7,'AWD'),
      ('bmw','3 Series','car','sedan','320d / 330e / M340i',2005,null,2000,'Automatic','diesel/plug-in hybrid',5,'RWD/AWD'),
      ('bmw','5 Series','car','sedan','520d / 530e / 530i',2005,null,2000,'Automatic','diesel/plug-in hybrid',5,'RWD'),
      ('bmw','7 Series','car','sedan','730Ld / 740Le / 750e',2005,null,3000,'Automatic','diesel/plug-in hybrid',5,'RWD/AWD'),
      ('bmw','X1','car','suv','sDrive18i / sDrive20d',2009,null,1500,'Automatic','petrol/diesel',5,'FWD/AWD'),
      ('bmw','X3','car','suv','xDrive20d / xDrive30e',2005,null,2000,'Automatic','diesel/plug-in hybrid',5,'AWD'),
      ('bmw','X5','car','suv','xDrive30d / xDrive45e / xDrive50e',2005,null,3000,'Automatic','diesel/plug-in hybrid',5,'AWD'),
      ('bmw','i4','car','sedan','eDrive35 / eDrive40 / M50',2022,null,null,'Automatic','electric',5,'RWD/AWD'),
      ('bmw','iX','car','suv','xDrive40 / xDrive50',2021,null,null,'Automatic','electric',5,'AWD'),
      ('audi','A3','car','sedan','35 TFSI / Sportback',2005,null,1400,'Automatic','petrol',5,'FWD'),
      ('audi','A4','car','sedan','35 TFSI / 45 TFSI quattro',2005,null,2000,'Automatic','petrol',5,'FWD/AWD'),
      ('audi','A6','car','sedan','45 TFSI quattro',2005,null,2000,'Automatic','petrol',5,'AWD'),
      ('audi','Q2','car','suv','35 TFSI',2017,null,1400,'Automatic','petrol',5,'FWD'),
      ('audi','Q3','car','suv','35 TFSI / Sportback',2012,null,1400,'Automatic','petrol',5,'FWD/AWD'),
      ('audi','Q5','car','suv','45 TFSI quattro',2009,null,2000,'Automatic','petrol',5,'AWD'),
      ('audi','Q7','car','suv','45 TDI / 55 TFSI',2006,null,3000,'Automatic','diesel/petrol',7,'AWD'),
      ('volkswagen','Golf','car','hatchback','TSI / GTI / R',2005,null,1400,'Automatic','petrol',5,'FWD/AWD'),
      ('volkswagen','Beetle','car','hatchback','TSI',2005,2019,1200,'Automatic','petrol',4,'FWD'),
      ('volkswagen','Passat','car','sedan','TSI / Variant',2005,2022,1800,'Automatic','petrol',5,'FWD'),
      ('volkswagen','Tiguan','car','suv','TSI / Allspace',2008,null,1400,'Automatic','petrol',7,'FWD/AWD'),
      ('volkswagen','Caravelle','van','van','Comfortline / Highline',2005,null,2000,'Automatic','diesel',7,'FWD'),
      ('volvo','S60','car','sedan','T4 / T8 Recharge',2005,null,2000,'Automatic','petrol/plug-in hybrid',5,'FWD/AWD'),
      ('volvo','S90','car','sedan','T8 Recharge',2017,null,2000,'Automatic','plug-in hybrid',5,'AWD'),
      ('volvo','XC40','car','suv','T5 / Recharge / EX40',2018,null,null,'Automatic','petrol/electric',5,'FWD/AWD'),
      ('volvo','XC60','car','suv','D4 / T8 Recharge',2008,null,2000,'Automatic','diesel/plug-in hybrid',5,'AWD'),
      ('volvo','XC90','car','suv','D5 / T8 Recharge',2005,null,2000,'Automatic','diesel/plug-in hybrid',7,'AWD'),
      ('byd','Dolphin','car','hatchback','Standard Range / Extended Range',2023,null,null,'Automatic','electric',5,'FWD'),
      ('byd','Atto 3','car','suv','Standard Range / Extended Range',2022,null,null,'Automatic','electric',5,'FWD'),
      ('byd','Seal','car','sedan','Dynamic / Premium / Performance',2023,null,null,'Automatic','electric',5,'RWD/AWD'),
      ('byd','Sealion 6','car','suv','DM-i',2024,null,1500,'Automatic','plug-in hybrid',5,'FWD'),
      ('byd','Sealion 7','car','suv','Premium / Performance',2025,null,null,'Automatic','electric',5,'RWD/AWD'),
      ('byd','M6','van','mpv','Standard / Extended Range',2024,null,null,'Automatic','electric',7,'FWD'),
      ('byd','e6','car','mpv','EV',2021,null,null,'Automatic','electric',5,'FWD'),
      ('gwm','Haval H6','car','suv','HEV / PHEV / Pro / Ultra',2021,null,1500,'Automatic','hybrid/plug-in hybrid',5,'FWD'),
      ('gwm','Haval Jolion','car','suv','HEV / Sport',2021,null,1500,'Automatic','hybrid',5,'FWD'),
      ('gwm','Tank 300','car','suv','HEV / Diesel / Ultra',2023,null,2000,'Automatic','petrol/hybrid/diesel',5,'4WD'),
      ('gwm','Tank 500','car','suv','HEV / Diesel',2023,null,2000,'Automatic','hybrid/diesel',7,'4WD'),
      ('gwm','Poer','car','pickup','Commercial / Passenger',2021,null,2000,'Automatic','diesel',5,'RWD/4WD'),
      ('ora','Good Cat','car','hatchback','Pro / Ultra / GT',2021,null,null,'Automatic','electric',5,'FWD'),
      ('ora','ORA 07','car','sedan','Long Range / Performance',2023,null,null,'Automatic','electric',5,'FWD/AWD'),
      ('chery','Omoda C5','car','suv','Comfort / Luxury / Ultimate',2023,null,1500,'Automatic','petrol',5,'FWD'),
      ('chery','Omoda E5','car','suv','EV',2024,null,null,'Automatic','electric',5,'FWD'),
      ('chery','Jaecoo 6','car','suv','EV',2024,null,null,'Automatic','electric',5,'RWD/AWD'),
      ('chery','Jaecoo 7','car','suv','PHEV / AWD',2024,null,1500,'Automatic','plug-in hybrid',5,'FWD/AWD'),
      ('aion','Y Plus','car','suv','490 Elite / Premium',2023,null,null,'Automatic','electric',5,'FWD'),
      ('aion','ES','car','sedan','EV',2024,null,null,'Automatic','electric',5,'FWD'),
      ('aion','V','car','suv','EV',2025,null,null,'Automatic','electric',5,'FWD'),
      ('neta','V','car','hatchback','EV',2022,2024,null,'Automatic','electric',5,'FWD'),
      ('neta','V-II','car','hatchback','EV',2024,null,null,'Automatic','electric',5,'FWD'),
      ('neta','X','car','suv','EV',2024,null,null,'Automatic','electric',5,'FWD'),
      ('neta','S','car','sedan','EV',2024,null,null,'Automatic','electric',5,'RWD'),
      ('changan','Deepal S07','car','suv','EV / REEV',2023,null,null,'Automatic','electric/range extender',5,'RWD'),
      ('changan','Deepal L07','car','sedan','EV / REEV',2023,null,null,'Automatic','electric/range extender',5,'RWD'),
      ('geely','EX5','car','suv','EV',2025,null,null,'Automatic','electric',5,'FWD'),
      ('geely','Coolray','car','suv','Sport / Premium',2019,null,1500,'Automatic','petrol',5,'FWD'),
      ('dfsk','Glory 560','car','suv','Standard',2019,null,1500,'Manual/Automatic','petrol',7,'FWD'),
      ('dfsk','Glory 580','car','suv','Standard',2019,null,1500,'Automatic','petrol',7,'FWD'),
      ('dfsk','EC31','van','van','EV',2023,null,null,'Automatic','electric',2,'RWD'),
      ('foton','Tunland','car','pickup','Single Cab / Double Cab',2012,null,2800,'Manual','diesel',5,'RWD/4WD'),
      ('foton','Toano','van','van','Standard',2015,null,2800,'Manual','diesel',12,'RWD'),
      ('honda','Wave 110i','motorcycle','underbone','Standard / Disc Brake',2005,null,110,'Manual','petrol',2,null),
      ('honda','Wave 125i','motorcycle','underbone','Standard / LED',2005,null,125,'Manual','petrol',2,null),
      ('honda','Dream','motorcycle','underbone','Standard',2005,null,110,'Manual','petrol',2,null),
      ('honda','Super Cub','motorcycle','underbone','Standard',2018,null,110,'Manual','petrol',2,null),
      ('honda','Scoopy','scooter','scooter','Standard / Club 12',2009,null,110,'Automatic','petrol',2,null),
      ('honda','Click 125i','scooter','scooter','Standard',2006,null,125,'Automatic','petrol',2,null),
      ('honda','Click 160','scooter','scooter','ABS',2022,null,157,'Automatic','petrol',2,null),
      ('honda','PCX 150','scooter','scooter','Standard',2010,2020,150,'Automatic','petrol',2,null),
      ('honda','PCX 160','scooter','scooter','Standard / ABS / e:HEV',2021,null,157,'Automatic','petrol/hybrid',2,null),
      ('honda','ADV 150','scooter','scooter','Standard',2019,2022,150,'Automatic','petrol',2,null),
      ('honda','ADV 160','scooter','scooter','ABS',2022,null,157,'Automatic','petrol',2,null),
      ('honda','Forza 300','scooter','maxi scooter','Standard',2013,2020,279,'Automatic','petrol',2,null),
      ('honda','Forza 350','scooter','maxi scooter','Standard / Roadsync',2020,null,330,'Automatic','petrol',2,null),
      ('honda','CBR150R','motorcycle','sport','Standard / ABS',2005,null,150,'Manual','petrol',2,null),
      ('honda','CBR500R','motorcycle','sport','Standard / ABS',2013,null,471,'Manual','petrol',2,null),
      ('honda','CB650R','motorcycle','naked','Standard / E-Clutch',2019,null,649,'Manual','petrol',2,null),
      ('honda','Rebel 300','motorcycle','cruiser','Standard',2017,null,286,'Manual','petrol',2,null),
      ('honda','Rebel 500','motorcycle','cruiser','Standard',2017,null,471,'Manual','petrol',2,null),
      ('honda','CRF250L','motorcycle','dual sport','Standard / Rally',2012,2020,250,'Manual','petrol',2,null),
      ('honda','CRF300L','motorcycle','dual sport','Standard / Rally',2021,null,286,'Manual','petrol',2,null),
      ('yamaha','Finn','motorcycle','underbone','Standard',2017,null,115,'Manual','petrol',2,null),
      ('yamaha','Mio','scooter','scooter','Standard / 115i',2005,2018,115,'Automatic','petrol',2,null),
      ('yamaha','Fino','scooter','scooter','Standard / Hybrid',2007,2023,125,'Automatic','petrol',2,null),
      ('yamaha','Grand Filano','scooter','scooter','Hybrid',2014,null,125,'Automatic','petrol/hybrid',2,null),
      ('yamaha','Aerox','scooter','scooter','Standard / ABS',2016,null,155,'Automatic','petrol',2,null),
      ('yamaha','NMAX','scooter','maxi scooter','Standard / Connected / Tech Max',2015,null,155,'Automatic','petrol',2,null),
      ('yamaha','XMAX','scooter','maxi scooter','Connected',2017,null,292,'Automatic','petrol',2,null),
      ('yamaha','R15','motorcycle','sport','Standard / Connected',2008,null,155,'Manual','petrol',2,null),
      ('yamaha','R3','motorcycle','sport','Standard',2015,null,321,'Manual','petrol',2,null),
      ('yamaha','MT-15','motorcycle','naked','Standard',2018,null,155,'Manual','petrol',2,null),
      ('yamaha','MT-03','motorcycle','naked','Standard',2016,null,321,'Manual','petrol',2,null),
      ('yamaha','MT-07','motorcycle','naked','Standard / Y-AMT',2014,null,689,'Manual/Automatic','petrol',2,null),
      ('kawasaki','Ninja 250','motorcycle','sport','Standard / ABS',2008,null,249,'Manual','petrol',2,null),
      ('kawasaki','Ninja 400','motorcycle','sport','Standard / SE',2018,null,399,'Manual','petrol',2,null),
      ('kawasaki','Ninja 650','motorcycle','sport touring','Standard',2006,null,649,'Manual','petrol',2,null),
      ('kawasaki','Z250','motorcycle','naked','Standard',2013,null,249,'Manual','petrol',2,null),
      ('kawasaki','Z400','motorcycle','naked','Standard',2019,null,399,'Manual','petrol',2,null),
      ('kawasaki','Z650','motorcycle','naked','Standard',2017,null,649,'Manual','petrol',2,null),
      ('kawasaki','Z900','motorcycle','naked','Standard / SE',2017,null,948,'Manual','petrol',2,null),
      ('kawasaki','Versys 650','motorcycle','adventure touring','Standard',2007,null,649,'Manual','petrol',2,null),
      ('kawasaki','KLX150','motorcycle','dual sport','Standard / BF',2009,null,144,'Manual','petrol',2,null),
      ('kawasaki','KLX230','motorcycle','dual sport','Standard / SE',2019,null,233,'Manual','petrol',2,null),
      ('suzuki','Smash','motorcycle','underbone','Standard',2005,null,115,'Manual','petrol',2,null),
      ('suzuki','Raider R150','motorcycle','underbone','Standard',2005,null,150,'Manual','petrol',2,null),
      ('suzuki','Burgman 200','scooter','maxi scooter','Standard',2014,null,200,'Automatic','petrol',2,null),
      ('suzuki','Burgman 400','scooter','maxi scooter','Standard',2005,null,400,'Automatic','petrol',2,null),
      ('suzuki','GSX-R150','motorcycle','sport','Standard',2017,null,150,'Manual','petrol',2,null),
      ('suzuki','GSX-S150','motorcycle','naked','Standard',2017,null,150,'Manual','petrol',2,null),
      ('suzuki','V-Strom 650','motorcycle','adventure touring','Standard / XT',2005,null,645,'Manual','petrol',2,null),
      ('suzuki','Hayabusa','motorcycle','sport touring','Standard',2005,null,1340,'Manual','petrol',2,null),
      ('ktm','Duke 200','motorcycle','naked','Standard',2012,null,199,'Manual','petrol',2,null),
      ('ktm','Duke 390','motorcycle','naked','Standard',2013,null,373,'Manual','petrol',2,null),
      ('ktm','RC 390','motorcycle','sport','Standard',2014,null,373,'Manual','petrol',2,null),
      ('ktm','390 Adventure','motorcycle','adventure','Standard / SW',2020,null,373,'Manual','petrol',2,null),
      ('royal-enfield','Classic 350','motorcycle','classic','Standard / Signals',2021,null,349,'Manual','petrol',2,null),
      ('royal-enfield','Meteor 350','motorcycle','cruiser','Fireball / Stellar / Supernova',2021,null,349,'Manual','petrol',2,null),
      ('royal-enfield','Hunter 350','motorcycle','roadster','Metro / Retro',2022,null,349,'Manual','petrol',2,null),
      ('royal-enfield','Himalayan','motorcycle','adventure','411 / 450',2016,null,452,'Manual','petrol',2,null),
      ('royal-enfield','Interceptor 650','motorcycle','roadster','Standard',2018,null,648,'Manual','petrol',2,null),
      ('royal-enfield','Continental GT 650','motorcycle','cafe racer','Standard',2018,null,648,'Manual','petrol',2,null),
      ('cfmoto','250NK','motorcycle','naked','Standard',2018,null,249,'Manual','petrol',2,null),
      ('cfmoto','300NK','motorcycle','naked','Standard',2020,null,292,'Manual','petrol',2,null),
      ('cfmoto','450SR','motorcycle','sport','Standard / S',2023,null,449,'Manual','petrol',2,null),
      ('cfmoto','650NK','motorcycle','naked','Standard',2017,null,649,'Manual','petrol',2,null),
      ('cfmoto','700CL-X','motorcycle','scrambler','Heritage / Sport',2021,null,693,'Manual','petrol',2,null),
      ('cfmoto','800MT','motorcycle','adventure touring','Sport / Touring',2021,null,799,'Manual','petrol',2,null),
      ('zontes','310R','motorcycle','naked','Standard',2018,null,312,'Manual','petrol',2,null),
      ('zontes','310X','motorcycle','sport touring','Standard',2018,null,312,'Manual','petrol',2,null),
      ('zontes','350D','scooter','maxi scooter','Standard',2023,null,349,'Automatic','petrol',2,null),
      ('benelli','TNT 135','motorcycle','mini bike','Standard',2017,null,135,'Manual','petrol',2,null),
      ('benelli','TNT 300','motorcycle','naked','Standard',2015,null,300,'Manual','petrol',2,null),
      ('benelli','TRK 251','motorcycle','adventure touring','Standard',2018,null,249,'Manual','petrol',2,null),
      ('benelli','TRK 502','motorcycle','adventure touring','Standard / X',2017,null,500,'Manual','petrol',2,null),
      ('benelli','Leoncino 500','motorcycle','scrambler','Standard / Trail',2017,null,500,'Manual','petrol',2,null),
      ('gpx','Demon','motorcycle','mini bike','150 / GR',2015,null,150,'Manual','petrol',2,null),
      ('gpx','Legend','motorcycle','classic','150 / 250 / Twin',2016,null,250,'Manual','petrol',2,null),
      ('gpx','Drone','scooter','scooter','Standard / Keyless',2020,null,150,'Automatic','petrol',2,null),
      ('gpx','GR200R','motorcycle','sport','Standard',2020,null,198,'Manual','petrol',2,null),
      ('gpx','Tuscany','scooter','scooter','150',2022,null,150,'Automatic','petrol',2,null)
    ) as v(make_slug, model_name, category_code, body_type, trim_name, year_from, year_to, engine_cc, transmission, fuel_type, seating_capacity, drivetrain)
  loop
    select id into make_uuid from public.vehicle_makes where slug = seed.make_slug;

    insert into public.vehicle_models (make_id, name, category_code, body_type, is_active)
    values (make_uuid, seed.model_name, seed.category_code, seed.body_type, true)
    on conflict (make_id, name) do update set
      category_code = excluded.category_code,
      body_type = excluded.body_type,
      is_active = true
    returning id into model_uuid;

    insert into public.vehicle_trims (
      model_id, name, year_from, year_to, engine_cc, transmission, fuel_type, seating_capacity, drivetrain, is_active
    )
    select
      model_uuid,
      seed.trim_name,
      seed.year_from,
      seed.year_to,
      seed.engine_cc,
      seed.transmission,
      seed.fuel_type,
      seed.seating_capacity,
      seed.drivetrain,
      true
    where not exists (
      select 1
      from public.vehicle_trims trim
      where trim.model_id = model_uuid
        and trim.name = seed.trim_name
        and trim.year_from = seed.year_from
        and coalesce(trim.year_to, 9999) = coalesce(seed.year_to, 9999)
    );
  end loop;
end $$;
